// Domain-based subject structure
// 5 Main Domains: Placement Prep, Frontend, Backend, AIML, Stax Interview

export type Domain = 'placement' | 'frontend' | 'backend' | 'aiml' | 'stax-interview'

export type Subject = 
  // Placement Prep Domain
  | 'cpp' | 'java' | 'python' | 'dsa' | 'oops' | 'dbms' | 'os' | 'cn' | 'system-design'
  // Frontend Domain
  | 'html' | 'css' | 'javascript' | 'react' | 'angular' | 'vue' | 'nextjs' | 'typescript'
  // Backend Domain
  | 'nodejs' | 'express' | 'django' | 'flask' | 'spring' | 'nestjs' | 'mongodb' | 'postgresql' | 'redis' | 'docker' | 'kubernetes'
  // AIML Domain
  | 'ml-basics' | 'deep-learning' | 'neural-networks' | 'nlp' | 'computer-vision' | 'tensorflow' | 'pytorch' | 'data-science'

export interface SubTopic {
  id: string
  name: string
  description: string
  locked: boolean
  completed: boolean
  xpReward: number
  order: number
  youtubeVideos?: string[] // YouTube video IDs for this topic
}

export interface Unit {
  id: string
  name: string
  description: string
  locked: boolean
  completed: boolean
  xpReward: number
  subtopics: SubTopic[]
}

export interface SubjectConfig {
  id: Subject
  name: string
  icon: string
  color: string
  domain: Domain
  units: Unit[]
}

export interface DomainConfig {
  id: Domain
  name: string
  description: string
  icon: string
  color: string
  subjects: Subject[]
}

export const DOMAINS: Record<Domain, DomainConfig> = {
  placement: {
    id: 'placement',
    name: 'Placement & Job Preparation',
    description: 'Complete CS preparation for product-based companies',
    icon: '🎯',
    color: 'neon-cyan',
    subjects: ['cpp', 'java', 'python', 'dsa', 'oops', 'dbms', 'os', 'cn', 'system-design']
  },
  frontend: {
    id: 'frontend',
    name: 'Frontend Technologies',
    description: 'Master modern frontend development',
    icon: '🎨',
    color: 'neon-purple',
    subjects: ['html', 'css', 'javascript', 'react', 'angular', 'vue', 'nextjs', 'typescript']
  },
  backend: {
    id: 'backend',
    name: 'Backend Technologies',
    description: 'Build scalable server-side applications',
    icon: '⚙️',
    color: 'neon-green',
    subjects: ['nodejs', 'express', 'django', 'flask', 'spring', 'nestjs', 'mongodb', 'postgresql', 'redis', 'docker', 'kubernetes']
  },
  aiml: {
    id: 'aiml',
    name: 'AI & Machine Learning',
    description: 'Master AI/ML and data science',
    icon: '🤖',
    color: 'neon-pink',
    subjects: ['ml-basics', 'deep-learning', 'neural-networks', 'nlp', 'computer-vision', 'tensorflow', 'pytorch', 'data-science']
  },
  'stax-interview': {
    id: 'stax-interview',
    name: 'Stax AI Interviewer',
    description: 'Practice interviews with AI-powered voice conversations',
    icon: '🎤',
    color: 'neon-purple',
    subjects: [] // No subjects - this is a tool/feature
  }
}

export const SUBJECTS: Record<Subject, SubjectConfig> = {
  // ============ PLACEMENT PREP DOMAIN ============
  cpp: {
    id: 'cpp',
    name: 'C++ Programming',
    icon: '⚡',
    color: 'neon-cyan',
    domain: 'placement',
    units: [
      {
        id: 'basics',
        name: 'C++ Basics',
        description: 'Fundamentals of C++',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to C++', description: 'History and features', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['vLnPwxZdW4Y'] },
          { id: 'syntax', name: 'C++ Syntax', description: 'Basic syntax rules', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['ZzaPdXTrSb8'] },
          { id: 'variables', name: 'Variables & Data Types', description: 'int, float, char, bool', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['8jLOx1hD3_o'] },
          { id: 'operators', name: 'Operators', description: 'Arithmetic, logical, relational', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['I5srDu75h_M'] },
        ],
      },
      {
        id: 'control-flow',
        name: 'Control Flow',
        description: 'Conditionals and loops',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'if-else', name: 'If-Else Statements', description: 'Conditional logic', locked: true, completed: false, xpReward: 30, order: 1, youtubeVideos: ['1e3egcoXE94'] },
          { id: 'loops', name: 'Loops', description: 'for, while, do-while', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['RBSGKlAvoiM'] },
          { id: 'switch', name: 'Switch Statements', description: 'Multi-way branching', locked: true, completed: false, xpReward: 40, order: 3, youtubeVideos: ['ZzaPdXTrSb8'] },
          { id: 'break-continue', name: 'Break & Continue', description: 'Loop control', locked: true, completed: false, xpReward: 40, order: 4, youtubeVideos: ['RBSGKlAvoiM'] },
        ],
      },
      {
        id: 'functions',
        name: 'Functions',
        description: 'Reusable code blocks',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'function-basics', name: 'Function Basics', description: 'Defining and calling', locked: true, completed: false, xpReward: 30, order: 1, youtubeVideos: ['8jLOx1hD3_o'] },
          { id: 'parameters', name: 'Parameters & Arguments', description: 'Passing data', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['8jLOx1hD3_o'] },
          { id: 'return', name: 'Return Values', description: 'Getting results', locked: true, completed: false, xpReward: 40, order: 3, youtubeVideos: ['8jLOx1hD3_o'] },
          { id: 'overloading', name: 'Function Overloading', description: 'Multiple definitions', locked: true, completed: false, xpReward: 40, order: 4, youtubeVideos: ['8jLOx1hD3_o'] },
        ],
      },
      {
        id: 'oop',
        name: 'Object-Oriented Programming',
        description: 'Classes, objects, inheritance',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'classes', name: 'Classes & Objects', description: 'OOP fundamentals', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'constructors', name: 'Constructors & Destructors', description: 'Object initialization', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'inheritance', name: 'Inheritance', description: 'Code reuse', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'polymorphism', name: 'Polymorphism', description: 'Runtime and compile-time', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['wN0x9eZLix4'] },
        ],
      },
      {
        id: 'stl',
        name: 'STL (Standard Template Library)',
        description: 'Containers, algorithms, iterators',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'containers', name: 'STL Containers', description: 'vector, list, map, set', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['Ly3T6XgMtNg'] },
          { id: 'algorithms', name: 'STL Algorithms', description: 'sort, find, transform', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['Ly3T6XgMtNg'] },
          { id: 'iterators', name: 'Iterators', description: 'Traversing containers', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['Ly3T6XgMtNg'] },
          { id: 'advanced-stl', name: 'Advanced STL', description: 'Custom comparators, lambdas', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['Ly3T6XgMtNg'] },
        ],
      },
    ],
  },
  java: {
    id: 'java',
    name: 'Java Programming',
    icon: '☕',
    color: 'neon-purple',
    domain: 'placement',
    units: [
      {
        id: 'basics',
        name: 'Java Basics',
        description: 'Fundamentals of Java',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Java', description: 'History and features', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'syntax', name: 'Java Syntax', description: 'Basic syntax rules', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'variables', name: 'Variables & Data Types', description: 'Primitive and reference types', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'operators', name: 'Operators', description: 'Arithmetic, logical, relational', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['eIrMbAQSU34'] },
        ],
      },
      {
        id: 'oop',
        name: 'OOP in Java',
        description: 'Classes, inheritance, polymorphism',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'classes', name: 'Classes & Objects', description: 'OOP fundamentals', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'inheritance', name: 'Inheritance', description: 'Extending classes', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'polymorphism', name: 'Polymorphism', description: 'Method overriding', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'interfaces', name: 'Interfaces & Abstract Classes', description: 'Contracts and abstraction', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['eIrMbAQSU34'] },
        ],
      },
      {
        id: 'collections',
        name: 'Collections Framework',
        description: 'Lists, maps, sets',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'arraylist', name: 'ArrayList', description: 'Dynamic arrays', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'hashmap', name: 'HashMap', description: 'Key-value pairs', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'hashset', name: 'HashSet', description: 'Unique elements', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'iterators', name: 'Iterators & Streams', description: 'Traversing collections', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['eIrMbAQSU34'] },
        ],
      },
      {
        id: 'multithreading',
        name: 'Multithreading',
        description: 'Concurrent programming',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'threads', name: 'Threads', description: 'Creating and managing threads', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'synchronization', name: 'Synchronization', description: 'Thread safety', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'executors', name: 'Executors & ThreadPool', description: 'Thread management', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['eIrMbAQSU34'] },
          { id: 'concurrent-collections', name: 'Concurrent Collections', description: 'Thread-safe collections', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['eIrMbAQSU34'] },
        ],
      },
    ],
  },
  python: {
    id: 'python',
    name: 'Python Programming',
    icon: '🐍',
    color: 'neon-green',
    domain: 'placement',
    units: [
      {
        id: 'basics',
        name: 'Python Basics',
        description: 'Fundamentals of Python',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Python', description: 'History and features', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'syntax', name: 'Python Syntax', description: 'Indentation, comments', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'variables', name: 'Variables & Data Types', description: 'Dynamic typing', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'operators', name: 'Operators', description: 'Math and logic', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['rfscVS0vtbw'] },
        ],
      },
      {
        id: 'data-structures',
        name: 'Data Structures',
        description: 'Lists, dicts, tuples, sets',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'lists', name: 'Lists', description: 'Ordered collections', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'tuples', name: 'Tuples', description: 'Immutable sequences', locked: true, completed: false, xpReward: 35, order: 2, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'dictionaries', name: 'Dictionaries', description: 'Key-value pairs', locked: true, completed: false, xpReward: 40, order: 3, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'sets', name: 'Sets', description: 'Unique collections', locked: true, completed: false, xpReward: 35, order: 4, youtubeVideos: ['rfscVS0vtbw'] },
        ],
      },
      {
        id: 'functions',
        name: 'Functions & Modules',
        description: 'Code organization',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'function-basics', name: 'Function Basics', description: 'def keyword', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'parameters', name: 'Parameters', description: 'args, kwargs', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'lambda', name: 'Lambda Functions', description: 'Anonymous functions', locked: true, completed: false, xpReward: 35, order: 3, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'modules', name: 'Modules & Packages', description: 'Importing code', locked: true, completed: false, xpReward: 35, order: 4, youtubeVideos: ['rfscVS0vtbw'] },
        ],
      },
      {
        id: 'oop',
        name: 'OOP in Python',
        description: 'Classes and objects',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'classes', name: 'Classes', description: 'Class definition', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'objects', name: 'Objects', description: 'Instances', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'inheritance', name: 'Inheritance', description: 'Extending classes', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['rfscVS0vtbw'] },
          { id: 'magic-methods', name: 'Magic Methods', description: '__init__, __str__', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['rfscVS0vtbw'] },
        ],
      },
    ],
  },
  dsa: {
    id: 'dsa',
    name: 'Data Structures & Algorithms',
    icon: '🔢',
    color: 'neon-pink',
    domain: 'placement',
    units: [
      {
        id: 'arrays',
        name: 'Arrays',
        description: 'Linear data structures',
        locked: false,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'intro', name: 'Introduction to Arrays', description: 'What are arrays?', locked: false, completed: false, xpReward: 30, order: 1, youtubeVideos: ['QJX22sKz4Fw'] },
          { id: 'operations', name: 'Array Operations', description: 'Access, insert, delete', locked: false, completed: false, xpReward: 40, order: 2, youtubeVideos: ['QJX22sKz4Fw'] },
          { id: 'searching', name: 'Searching in Arrays', description: 'Linear & Binary search', locked: false, completed: false, xpReward: 40, order: 3, youtubeVideos: ['pGU7TLqBAyI'] },
          { id: 'sorting', name: 'Sorting Arrays', description: 'Bubble, Selection, Insertion', locked: false, completed: false, xpReward: 40, order: 4, youtubeVideos: ['pGU7TLqBAyI'] },
        ],
      },
      {
        id: 'linked-lists',
        name: 'Linked Lists',
        description: 'Dynamic structures',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'singly', name: 'Singly Linked List', description: 'One-way connection', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['HdFG8L1sajw'] },
          { id: 'doubly', name: 'Doubly Linked List', description: 'Two-way connection', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['HdFG8L1sajw'] },
          { id: 'operations', name: 'LL Operations', description: 'Insert, delete, traverse', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['HdFG8L1sajw'] },
          { id: 'applications', name: 'Applications', description: 'Real-world uses', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['HdFG8L1sajw'] },
        ],
      },
      {
        id: 'trees',
        name: 'Trees',
        description: 'Hierarchical data',
        locked: true,
        completed: false,
        xpReward: 250,
        subtopics: [
          { id: 'binary-tree', name: 'Binary Tree', description: 'Two children max', locked: true, completed: false, xpReward: 60, order: 1, youtubeVideos: ['fPz40W9ftCk'] },
          { id: 'bst', name: 'Binary Search Tree', description: 'Sorted tree', locked: true, completed: false, xpReward: 60, order: 2, youtubeVideos: ['fPz40W9ftCk'] },
          { id: 'traversal', name: 'Tree Traversal', description: 'Inorder, Preorder, Postorder', locked: true, completed: false, xpReward: 65, order: 3, youtubeVideos: ['fPz40W9ftCk'] },
          { id: 'avl', name: 'AVL Trees', description: 'Self-balancing', locked: true, completed: false, xpReward: 65, order: 4, youtubeVideos: ['fPz40W9ftCk'] },
        ],
      },
      {
        id: 'graphs',
        name: 'Graphs',
        description: 'Network structures',
        locked: true,
        completed: false,
        xpReward: 250,
        subtopics: [
          { id: 'graph-intro', name: 'Graph Introduction', description: 'Vertices and edges', locked: true, completed: false, xpReward: 60, order: 1, youtubeVideos: ['tWVWeAqZ0Gw'] },
          { id: 'bfs', name: 'BFS (Breadth-First Search)', description: 'Level-order traversal', locked: true, completed: false, xpReward: 60, order: 2, youtubeVideos: ['tWVWeAqZ0Gw'] },
          { id: 'dfs', name: 'DFS (Depth-First Search)', description: 'Deep traversal', locked: true, completed: false, xpReward: 65, order: 3, youtubeVideos: ['tWVWeAqZ0Gw'] },
          { id: 'shortest-path', name: 'Shortest Path Algorithms', description: 'Dijkstra, Bellman-Ford', locked: true, completed: false, xpReward: 65, order: 4, youtubeVideos: ['tWVWeAqZ0Gw'] },
        ],
      },
      {
        id: 'sorting',
        name: 'Sorting Algorithms',
        description: 'Efficient ordering',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'quick-sort', name: 'Quick Sort', description: 'Divide & conquer', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['Hoixgm4-P4M'] },
          { id: 'merge-sort', name: 'Merge Sort', description: 'Divide & merge', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['4VqmGXwpBRg'] },
          { id: 'heap-sort', name: 'Heap Sort', description: 'Heap-based', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['MtQL_ll5ZhQ'] },
          { id: 'complexity', name: 'Time Complexity', description: 'Big O analysis', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['Mo4vesaut8g'] },
        ],
      },
      {
        id: 'dynamic-programming',
        name: 'Dynamic Programming',
        description: 'Optimization technique',
        locked: true,
        completed: false,
        xpReward: 250,
        subtopics: [
          { id: 'dp-intro', name: 'DP Introduction', description: 'Memoization and tabulation', locked: true, completed: false, xpReward: 60, order: 1, youtubeVideos: ['oBt53YbR9Kk'] },
          { id: 'dp-patterns', name: 'DP Patterns', description: 'Common patterns', locked: true, completed: false, xpReward: 60, order: 2, youtubeVideos: ['oBt53YbR9Kk'] },
          { id: 'dp-problems', name: 'DP Problems', description: 'Classic problems', locked: true, completed: false, xpReward: 65, order: 3, youtubeVideos: ['oBt53YbR9Kk'] },
          { id: 'advanced-dp', name: 'Advanced DP', description: 'Complex optimizations', locked: true, completed: false, xpReward: 65, order: 4, youtubeVideos: ['oBt53YbR9Kk'] },
        ],
      },
    ],
  },
  oops: {
    id: 'oops',
    name: 'Object-Oriented Programming',
    icon: '🎯',
    color: 'neon-blue',
    domain: 'placement',
    units: [
      {
        id: 'classes',
        name: 'Classes & Objects',
        description: 'Fundamentals',
        locked: false,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'class-concept', name: 'Class Concept', description: 'Blueprint', locked: false, completed: false, xpReward: 40, order: 1, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'objects', name: 'Objects', description: 'Instances', locked: false, completed: false, xpReward: 40, order: 2, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'attributes', name: 'Attributes', description: 'Properties', locked: false, completed: false, xpReward: 35, order: 3, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'methods', name: 'Methods', description: 'Behaviors', locked: false, completed: false, xpReward: 35, order: 4, youtubeVideos: ['wN0x9eZLix4'] },
        ],
      },
      {
        id: 'inheritance',
        name: 'Inheritance',
        description: 'Code reuse',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'single', name: 'Single Inheritance', description: 'One parent', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'multiple', name: 'Multiple Inheritance', description: 'Multiple parents', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'multilevel', name: 'Multilevel Inheritance', description: 'Chain of inheritance', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'overriding', name: 'Method Overriding', description: 'Customizing behavior', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['wN0x9eZLix4'] },
        ],
      },
      {
        id: 'polymorphism',
        name: 'Polymorphism',
        description: 'Many forms',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'compile-time', name: 'Compile-time Polymorphism', description: 'Method overloading', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'runtime', name: 'Runtime Polymorphism', description: 'Method overriding', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'virtual', name: 'Virtual Functions', description: 'Dynamic binding', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'abstract', name: 'Abstract Classes', description: 'Incomplete classes', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['wN0x9eZLix4'] },
        ],
      },
      {
        id: 'encapsulation',
        name: 'Encapsulation',
        description: 'Data hiding',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'access-control', name: 'Access Control', description: 'public, private, protected', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'getters', name: 'Getters', description: 'Reading data', locked: true, completed: false, xpReward: 35, order: 2, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'setters', name: 'Setters', description: 'Writing data', locked: true, completed: false, xpReward: 35, order: 3, youtubeVideos: ['wN0x9eZLix4'] },
          { id: 'data-protection', name: 'Data Protection', description: 'Security', locked: true, completed: false, xpReward: 40, order: 4, youtubeVideos: ['wN0x9eZLix4'] },
        ],
      },
    ],
  },
  dbms: {
    id: 'dbms',
    name: 'Database Management Systems',
    icon: '🗄️',
    color: 'neon-cyan',
    domain: 'placement',
    units: [
      {
        id: 'introduction',
        name: 'DBMS Introduction',
        description: 'Basics of databases',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'what-is-dbms', name: 'What is DBMS?', description: 'Database basics', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'advantages', name: 'Advantages', description: 'Why use DBMS', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'types', name: 'Database Types', description: 'Relational, NoSQL', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'architecture', name: 'DBMS Architecture', description: 'System design', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['kBdlM6hNDAE'] },
        ],
      },
      {
        id: 'sql',
        name: 'SQL Fundamentals',
        description: 'Query language',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'select', name: 'SELECT Queries', description: 'Retrieving data', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['HXV3zeQKqGY'] },
          { id: 'insert', name: 'INSERT Statements', description: 'Adding data', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['HXV3zeQKqGY'] },
          { id: 'update', name: 'UPDATE & DELETE', description: 'Modifying data', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['HXV3zeQKqGY'] },
          { id: 'joins', name: 'JOINs', description: 'Combining tables', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['HXV3zeQKqGY'] },
        ],
      },
      {
        id: 'normalization',
        name: 'Normalization',
        description: 'Database design',
        locked: true,
        completed: false,
        xpReward: 250,
        subtopics: [
          { id: '1nf', name: 'First Normal Form', description: '1NF', locked: true, completed: false, xpReward: 60, order: 1, youtubeVideos: ['GFQaEYEc8_8'] },
          { id: '2nf', name: 'Second Normal Form', description: '2NF', locked: true, completed: false, xpReward: 60, order: 2, youtubeVideos: ['GFQaEYEc8_8'] },
          { id: '3nf', name: 'Third Normal Form', description: '3NF', locked: true, completed: false, xpReward: 65, order: 3, youtubeVideos: ['GFQaEYEc8_8'] },
          { id: 'bcnf', name: 'BCNF', description: 'Boyce-Codd NF', locked: true, completed: false, xpReward: 65, order: 4, youtubeVideos: ['GFQaEYEc8_8'] },
        ],
      },
      {
        id: 'transactions',
        name: 'Transactions',
        description: 'ACID properties',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'acid', name: 'ACID Properties', description: 'Atomicity, Consistency', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'concurrency', name: 'Concurrency Control', description: 'Managing access', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'locks', name: 'Locks', description: 'Locking mechanisms', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'deadlock', name: 'Deadlock', description: 'Prevention & detection', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['kBdlM6hNDAE'] },
        ],
      },
      {
        id: 'indexing',
        name: 'Indexing',
        description: 'Performance optimization',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'b-tree', name: 'B-Tree Index', description: 'Balanced tree', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'hash', name: 'Hash Index', description: 'Hash-based', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'clustered', name: 'Clustered Index', description: 'Physical ordering', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['kBdlM6hNDAE'] },
          { id: 'optimization', name: 'Query Optimization', description: 'Improving performance', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['kBdlM6hNDAE'] },
        ],
      },
    ],
  },
  os: {
    id: 'os',
    name: 'Operating Systems',
    icon: '💻',
    color: 'neon-yellow',
    domain: 'placement',
    units: [
      {
        id: 'introduction',
        name: 'OS Introduction',
        description: 'Basics of operating systems',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'what-is-os', name: 'What is OS?', description: 'Operating system basics', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'functions', name: 'OS Functions', description: 'Core functions', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'types', name: 'Types of OS', description: 'Different OS types', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'architecture', name: 'OS Architecture', description: 'System structure', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['vBURTt97EkA'] },
        ],
      },
      {
        id: 'process-management',
        name: 'Process Management',
        description: 'Processes and threads',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'processes', name: 'Processes', description: 'Process concept', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'threads', name: 'Threads', description: 'Thread concept', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'scheduling', name: 'CPU Scheduling', description: 'Scheduling algorithms', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'synchronization', name: 'Process Synchronization', description: 'Race conditions', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['vBURTt97EkA'] },
        ],
      },
      {
        id: 'memory-management',
        name: 'Memory Management',
        description: 'Memory allocation',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'memory-basics', name: 'Memory Basics', description: 'Memory hierarchy', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'paging', name: 'Paging', description: 'Page-based memory', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'segmentation', name: 'Segmentation', description: 'Segment-based memory', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'virtual-memory', name: 'Virtual Memory', description: 'Memory abstraction', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['vBURTt97EkA'] },
        ],
      },
      {
        id: 'file-systems',
        name: 'File Systems',
        description: 'File management',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'file-concept', name: 'File Concept', description: 'File basics', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'directory', name: 'Directory Structure', description: 'File organization', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'allocation', name: 'File Allocation', description: 'Storage methods', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['vBURTt97EkA'] },
          { id: 'disk-scheduling', name: 'Disk Scheduling', description: 'I/O optimization', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['vBURTt97EkA'] },
        ],
      },
    ],
  },
  cn: {
    id: 'cn',
    name: 'Computer Networks',
    icon: '🌐',
    color: 'neon-blue',
    domain: 'placement',
    units: [
      {
        id: 'introduction',
        name: 'Networks Introduction',
        description: 'Basics of networking',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'network-basics', name: 'Network Basics', description: 'What are networks?', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'topology', name: 'Network Topology', description: 'Network layouts', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'types', name: 'Network Types', description: 'LAN, WAN, MAN', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'protocols', name: 'Network Protocols', description: 'Communication rules', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['qiQR5rTSshw'] },
        ],
      },
      {
        id: 'osi-model',
        name: 'OSI Model',
        description: '7-layer architecture',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'physical', name: 'Physical Layer', description: 'Layer 1', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'data-link', name: 'Data Link Layer', description: 'Layer 2', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'network', name: 'Network Layer', description: 'Layer 3', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'transport', name: 'Transport Layer', description: 'Layer 4', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['qiQR5rTSshw'] },
        ],
      },
      {
        id: 'tcp-ip',
        name: 'TCP/IP Model',
        description: 'Internet protocol suite',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'tcp', name: 'TCP Protocol', description: 'Reliable transmission', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'udp', name: 'UDP Protocol', description: 'Fast transmission', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'ip', name: 'IP Protocol', description: 'Internet protocol', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'routing', name: 'Routing', description: 'Path selection', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['qiQR5rTSshw'] },
        ],
      },
      {
        id: 'application-layer',
        name: 'Application Layer',
        description: 'HTTP, HTTPS, DNS',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'http', name: 'HTTP/HTTPS', description: 'Web protocols', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'dns', name: 'DNS', description: 'Domain name system', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'smtp', name: 'SMTP', description: 'Email protocol', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['qiQR5rTSshw'] },
          { id: 'ftp', name: 'FTP', description: 'File transfer', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['qiQR5rTSshw'] },
        ],
      },
    ],
  },
  'system-design': {
    id: 'system-design',
    name: 'System Design',
    icon: '🏗️',
    color: 'neon-orange',
    domain: 'placement',
    units: [
      {
        id: 'introduction',
        name: 'System Design Introduction',
        description: 'Basics of system design',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'what-is-sd', name: 'What is System Design?', description: 'System design basics', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'scalability', name: 'Scalability', description: 'Scaling systems', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'reliability', name: 'Reliability', description: 'System reliability', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'availability', name: 'Availability', description: 'Uptime and downtime', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['UzLMhqg3WcY'] },
        ],
      },
      {
        id: 'load-balancing',
        name: 'Load Balancing',
        description: 'Distributing traffic',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'lb-intro', name: 'Load Balancing Basics', description: 'What is load balancing?', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'lb-algorithms', name: 'LB Algorithms', description: 'Round-robin, least connections', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'lb-types', name: 'LB Types', description: 'Hardware vs software', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'lb-practices', name: 'Best Practices', description: 'Implementation tips', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['UzLMhqg3WcY'] },
        ],
      },
      {
        id: 'caching',
        name: 'Caching',
        description: 'Performance optimization',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'cache-intro', name: 'Caching Basics', description: 'What is caching?', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'cache-strategies', name: 'Cache Strategies', description: 'Write-through, write-back', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'cache-types', name: 'Cache Types', description: 'CDN, application cache', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'redis', name: 'Redis', description: 'In-memory cache', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['UzLMhqg3WcY'] },
        ],
      },
      {
        id: 'databases',
        name: 'Database Design',
        description: 'Data storage strategies',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'db-types', name: 'Database Types', description: 'SQL vs NoSQL', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'replication', name: 'Replication', description: 'Data replication', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'sharding', name: 'Sharding', description: 'Horizontal partitioning', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'consistency', name: 'Consistency Models', description: 'CAP theorem', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['UzLMhqg3WcY'] },
        ],
      },
      {
        id: 'messaging',
        name: 'Message Queues',
        description: 'Async communication',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'mq-intro', name: 'Message Queues', description: 'What are MQs?', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'kafka', name: 'Apache Kafka', description: 'Distributed streaming', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'rabbitmq', name: 'RabbitMQ', description: 'Message broker', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['UzLMhqg3WcY'] },
          { id: 'pub-sub', name: 'Pub-Sub Pattern', description: 'Publish-subscribe', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['UzLMhqg3WcY'] },
        ],
      },
    ],
  },
  
  // ============ FRONTEND DOMAIN ============
  html: {
    id: 'html',
    name: 'HTML',
    icon: '📄',
    color: 'neon-orange',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'HTML Basics',
        description: 'Fundamentals of HTML',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to HTML', description: 'What is HTML?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'structure', name: 'HTML Structure', description: 'Document structure', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'elements', name: 'HTML Elements', description: 'Tags and attributes', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'headings', name: 'Headings & Paragraphs', description: 'Text elements', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['UB1O30fR-EE'] },
        ],
      },
      {
        id: 'forms',
        name: 'Forms',
        description: 'User input',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'form-basics', name: 'Form Basics', description: 'Creating forms', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'input-types', name: 'Input Types', description: 'Text, email, password', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'validation', name: 'Form Validation', description: 'HTML5 validation', locked: true, completed: false, xpReward: 35, order: 3, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'advanced-forms', name: 'Advanced Forms', description: 'Complex inputs', locked: true, completed: false, xpReward: 35, order: 4, youtubeVideos: ['UB1O30fR-EE'] },
        ],
      },
      {
        id: 'semantic',
        name: 'Semantic HTML',
        description: 'Meaningful markup',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'semantic-tags', name: 'Semantic Tags', description: 'header, nav, article', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'accessibility', name: 'Accessibility', description: 'ARIA, alt text', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'seo', name: 'SEO Basics', description: 'Search optimization', locked: true, completed: false, xpReward: 35, order: 3, youtubeVideos: ['UB1O30fR-EE'] },
          { id: 'best-practices', name: 'Best Practices', description: 'HTML standards', locked: true, completed: false, xpReward: 35, order: 4, youtubeVideos: ['UB1O30fR-EE'] },
        ],
      },
    ],
  },
  css: {
    id: 'css',
    name: 'CSS',
    icon: '🎨',
    color: 'neon-blue',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'CSS Basics',
        description: 'Fundamentals of CSS',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to CSS', description: 'What is CSS?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['1PnVor36_40'] },
          { id: 'selectors', name: 'Selectors', description: 'Element, class, ID', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['1PnVor36_40'] },
          { id: 'properties', name: 'CSS Properties', description: 'Color, font, margin', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['1PnVor36_40'] },
          { id: 'box-model', name: 'Box Model', description: 'Margin, padding, border', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['1PnVor36_40'] },
        ],
      },
      {
        id: 'layout',
        name: 'Layout',
        description: 'Flexbox and Grid',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'flexbox', name: 'Flexbox', description: 'Flexible layouts', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['1PnVor36_40'] },
          { id: 'grid', name: 'CSS Grid', description: 'Grid layouts', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['1PnVor36_40'] },
          { id: 'positioning', name: 'Positioning', description: 'Relative, absolute, fixed', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['1PnVor36_40'] },
          { id: 'responsive', name: 'Responsive Design', description: 'Media queries', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['1PnVor36_40'] },
        ],
      },
      {
        id: 'advanced',
        name: 'Advanced CSS',
        description: 'Animations and transitions',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'animations', name: 'Animations', description: 'Keyframes and animation', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['1PnVor36_40'] },
          { id: 'transitions', name: 'Transitions', description: 'Smooth changes', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['1PnVor36_40'] },
          { id: 'transform', name: 'Transform', description: 'Rotate, scale, translate', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['1PnVor36_40'] },
          { id: 'preprocessors', name: 'CSS Preprocessors', description: 'SASS, LESS', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['1PnVor36_40'] },
        ],
      },
    ],
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    icon: '⚡',
    color: 'neon-yellow',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'JavaScript Basics',
        description: 'Fundamentals of JS',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to JavaScript', description: 'What is JavaScript?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'variables', name: 'Variables', description: 'let, const, var', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'data-types', name: 'Data Types', description: 'Primitive and reference types', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'operators', name: 'Operators', description: 'Arithmetic, logical, comparison', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['W6NZfCO5SIk'] },
        ],
      },
      {
        id: 'functions',
        name: 'Functions',
        description: 'Function declarations and expressions',
        locked: true,
        completed: false,
        xpReward: 150,
        subtopics: [
          { id: 'function-basics', name: 'Function Basics', description: 'Function declarations', locked: true, completed: false, xpReward: 40, order: 1, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'arrow-functions', name: 'Arrow Functions', description: 'ES6 arrow syntax', locked: true, completed: false, xpReward: 40, order: 2, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'closures', name: 'Closures', description: 'Scope and closures', locked: true, completed: false, xpReward: 35, order: 3, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'callbacks', name: 'Callbacks', description: 'Callback functions', locked: true, completed: false, xpReward: 35, order: 4, youtubeVideos: ['W6NZfCO5SIk'] },
        ],
      },
      {
        id: 'dom',
        name: 'DOM Manipulation',
        description: 'Working with the DOM',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'dom-intro', name: 'DOM Introduction', description: 'What is the DOM?', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'selectors', name: 'DOM Selectors', description: 'querySelector, getElementById', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'events', name: 'Event Handling', description: 'Event listeners', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'manipulation', name: 'DOM Manipulation', description: 'Creating and modifying elements', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['W6NZfCO5SIk'] },
        ],
      },
      {
        id: 'es6',
        name: 'ES6+ Features',
        description: 'Modern JavaScript',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'let-const', name: 'let and const', description: 'Block scoping', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'destructuring', name: 'Destructuring', description: 'Array and object destructuring', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'spread', name: 'Spread Operator', description: 'Spread and rest', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['W6NZfCO5SIk'] },
          { id: 'async', name: 'Async/Await', description: 'Asynchronous programming', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['W6NZfCO5SIk'] },
        ],
      },
    ],
  },
  react: {
    id: 'react',
    name: 'React',
    icon: '⚛️',
    color: 'neon-cyan',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'React Basics',
        description: 'Fundamentals of React',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to React', description: 'What is React?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'jsx', name: 'JSX', description: 'JavaScript XML', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'components', name: 'Components', description: 'Functional components', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'props', name: 'Props', description: 'Passing data', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['DLX62G4lc44'] },
        ],
      },
      {
        id: 'state',
        name: 'State Management',
        description: 'useState and useEffect',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'useState', name: 'useState Hook', description: 'Managing state', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'useEffect', name: 'useEffect Hook', description: 'Side effects', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'custom-hooks', name: 'Custom Hooks', description: 'Reusable logic', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'context', name: 'Context API', description: 'Global state', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['DLX62G4lc44'] },
        ],
      },
      {
        id: 'routing',
        name: 'Routing',
        description: 'React Router',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'router-basics', name: 'React Router Basics', description: 'Setting up routes', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'navigation', name: 'Navigation', description: 'Link and NavLink', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'params', name: 'URL Parameters', description: 'Dynamic routes', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'protected', name: 'Protected Routes', description: 'Route guards', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['DLX62G4lc44'] },
        ],
      },
      {
        id: 'advanced',
        name: 'Advanced React',
        description: 'Performance and patterns',
        locked: true,
        completed: false,
        xpReward: 250,
        subtopics: [
          { id: 'memo', name: 'React.memo', description: 'Component memoization', locked: true, completed: false, xpReward: 60, order: 1, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'useMemo', name: 'useMemo & useCallback', description: 'Optimization hooks', locked: true, completed: false, xpReward: 60, order: 2, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'redux', name: 'Redux', description: 'State management library', locked: true, completed: false, xpReward: 65, order: 3, youtubeVideos: ['DLX62G4lc44'] },
          { id: 'testing', name: 'Testing', description: 'Jest and React Testing Library', locked: true, completed: false, xpReward: 65, order: 4, youtubeVideos: ['DLX62G4lc44'] },
        ],
      },
    ],
  },
  angular: {
    id: 'angular',
    name: 'Angular',
    icon: '🅰️',
    color: 'neon-red',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'Angular Basics',
        description: 'Fundamentals of Angular',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Angular', description: 'What is Angular?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'components', name: 'Components', description: 'Component architecture', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'modules', name: 'Modules', description: 'NgModule', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'templates', name: 'Templates', description: 'HTML templates', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['k5E2AVpwsko'] },
        ],
      },
      {
        id: 'data-binding',
        name: 'Data Binding',
        description: 'Two-way data binding',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'interpolation', name: 'Interpolation', description: 'String interpolation', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'property-binding', name: 'Property Binding', description: 'Binding properties', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'event-binding', name: 'Event Binding', description: 'Handling events', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'two-way', name: 'Two-way Binding', description: 'ngModel', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['k5E2AVpwsko'] },
        ],
      },
      {
        id: 'services',
        name: 'Services & Dependency Injection',
        description: 'Service architecture',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'services', name: 'Services', description: 'Creating services', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'di', name: 'Dependency Injection', description: 'DI pattern', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'http', name: 'HTTP Client', description: 'Making API calls', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'rxjs', name: 'RxJS', description: 'Reactive programming', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['k5E2AVpwsko'] },
        ],
      },
      {
        id: 'routing',
        name: 'Routing',
        description: 'Angular Router',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'router-basics', name: 'Router Basics', description: 'Setting up routes', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'navigation', name: 'Navigation', description: 'RouterLink', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'guards', name: 'Route Guards', description: 'CanActivate, CanDeactivate', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['k5E2AVpwsko'] },
          { id: 'lazy-loading', name: 'Lazy Loading', description: 'Code splitting', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['k5E2AVpwsko'] },
        ],
      },
    ],
  },
  vue: {
    id: 'vue',
    name: 'Vue.js',
    icon: '💚',
    color: 'neon-green',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'Vue Basics',
        description: 'Fundamentals of Vue',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Vue', description: 'What is Vue?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'directives', name: 'Directives', description: 'v-if, v-for, v-bind', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'components', name: 'Components', description: 'Component system', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'props', name: 'Props & Events', description: 'Component communication', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['4deVCNJq3qc'] },
        ],
      },
      {
        id: 'reactivity',
        name: 'Reactivity',
        description: 'Reactive data',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'data', name: 'Data & Methods', description: 'Reactive data', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'computed', name: 'Computed Properties', description: 'Derived state', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'watchers', name: 'Watchers', description: 'Watching changes', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'ref-reactive', name: 'ref & reactive', description: 'Composition API', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['4deVCNJq3qc'] },
        ],
      },
      {
        id: 'routing',
        name: 'Vue Router',
        description: 'Client-side routing',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'router-basics', name: 'Router Basics', description: 'Setting up routes', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'navigation', name: 'Navigation', description: 'router-link', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'params', name: 'Route Parameters', description: 'Dynamic routes', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['4deVCNJq3qc'] },
          { id: 'guards', name: 'Navigation Guards', description: 'Route protection', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['4deVCNJq3qc'] },
        ],
      },
    ],
  },
  nextjs: {
    id: 'nextjs',
    name: 'Next.js',
    icon: '▲',
    color: 'neon-cyan',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'Next.js Basics',
        description: 'Fundamentals of Next.js',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Next.js', description: 'What is Next.js?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'routing', name: 'File-based Routing', description: 'Pages and routes', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'ssr', name: 'Server-Side Rendering', description: 'SSR basics', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'ssg', name: 'Static Site Generation', description: 'SSG basics', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['Sklc_fQBmcs'] },
        ],
      },
      {
        id: 'advanced',
        name: 'Advanced Next.js',
        description: 'API routes and optimization',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'api-routes', name: 'API Routes', description: 'Backend in Next.js', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'middleware', name: 'Middleware', description: 'Request handling', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'optimization', name: 'Optimization', description: 'Image, font optimization', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['Sklc_fQBmcs'] },
          { id: 'deployment', name: 'Deployment', description: 'Vercel deployment', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['Sklc_fQBmcs'] },
        ],
      },
    ],
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    icon: '📘',
    color: 'neon-blue',
    domain: 'frontend',
    units: [
      {
        id: 'basics',
        name: 'TypeScript Basics',
        description: 'Fundamentals of TypeScript',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to TypeScript', description: 'What is TypeScript?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'types', name: 'Basic Types', description: 'string, number, boolean', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'interfaces', name: 'Interfaces', description: 'Defining interfaces', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'classes', name: 'Classes', description: 'TypeScript classes', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['WBPrJSw7yQA'] },
        ],
      },
      {
        id: 'advanced',
        name: 'Advanced TypeScript',
        description: 'Generics and utilities',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'generics', name: 'Generics', description: 'Generic types', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'utility', name: 'Utility Types', description: 'Partial, Pick, Omit', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'decorators', name: 'Decorators', description: 'Class decorators', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['WBPrJSw7yQA'] },
          { id: 'advanced-types', name: 'Advanced Types', description: 'Union, intersection types', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['WBPrJSw7yQA'] },
        ],
      },
    ],
  },
  
  // ============ BACKEND DOMAIN ============
  nodejs: {
    id: 'nodejs',
    name: 'Node.js',
    icon: '🟢',
    color: 'neon-green',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Node.js Basics',
        description: 'Fundamentals of Node.js',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Node.js', description: 'What is Node.js?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'modules', name: 'Modules', description: 'CommonJS modules', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'npm', name: 'NPM', description: 'Package management', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'file-system', name: 'File System', description: 'fs module', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['TlB_eWDSMt4'] },
        ],
      },
      {
        id: 'async',
        name: 'Asynchronous Programming',
        description: 'Callbacks, promises, async/await',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'callbacks', name: 'Callbacks', description: 'Callback pattern', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'promises', name: 'Promises', description: 'Promise API', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'async-await', name: 'Async/Await', description: 'Modern async', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'event-loop', name: 'Event Loop', description: 'Node.js event loop', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['TlB_eWDSMt4'] },
        ],
      },
      {
        id: 'streams',
        name: 'Streams',
        description: 'Streaming data',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'stream-basics', name: 'Stream Basics', description: 'What are streams?', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'readable', name: 'Readable Streams', description: 'Reading data', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'writable', name: 'Writable Streams', description: 'Writing data', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['TlB_eWDSMt4'] },
          { id: 'transform', name: 'Transform Streams', description: 'Data transformation', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['TlB_eWDSMt4'] },
        ],
      },
    ],
  },
  express: {
    id: 'express',
    name: 'Express.js',
    icon: '🚂',
    color: 'neon-gray',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Express Basics',
        description: 'Fundamentals of Express',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Express', description: 'What is Express?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'routing', name: 'Routing', description: 'Route handlers', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'middleware', name: 'Middleware', description: 'Request processing', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'templates', name: 'Templates', description: 'View engines', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['SccSCuHhOw0'] },
        ],
      },
      {
        id: 'api',
        name: 'REST API',
        description: 'Building REST APIs',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'rest-basics', name: 'REST Basics', description: 'REST principles', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'crud', name: 'CRUD Operations', description: 'Create, Read, Update, Delete', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'authentication', name: 'Authentication', description: 'JWT, sessions', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['SccSCuHhOw0'] },
          { id: 'error-handling', name: 'Error Handling', description: 'Error middleware', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['SccSCuHhOw0'] },
        ],
      },
    ],
  },
  django: {
    id: 'django',
    name: 'Django',
    icon: '🎸',
    color: 'neon-green',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Django Basics',
        description: 'Fundamentals of Django',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Django', description: 'What is Django?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'models', name: 'Models', description: 'Database models', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'views', name: 'Views', description: 'View functions', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'templates', name: 'Templates', description: 'Django templates', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['rHux0gMZ3Eg'] },
        ],
      },
      {
        id: 'orm',
        name: 'Django ORM',
        description: 'Object-Relational Mapping',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'queries', name: 'Queries', description: 'Database queries', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'relationships', name: 'Relationships', description: 'Foreign keys, many-to-many', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'migrations', name: 'Migrations', description: 'Database migrations', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['rHux0gMZ3Eg'] },
          { id: 'admin', name: 'Admin Panel', description: 'Django admin', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['rHux0gMZ3Eg'] },
        ],
      },
    ],
  },
  flask: {
    id: 'flask',
    name: 'Flask',
    icon: '🌶️',
    color: 'neon-red',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Flask Basics',
        description: 'Fundamentals of Flask',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Flask', description: 'What is Flask?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['Z1RJmh_OqeA'] },
          { id: 'routing', name: 'Routing', description: 'URL routing', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['Z1RJmh_OqeA'] },
          { id: 'templates', name: 'Templates', description: 'Jinja2 templates', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['Z1RJmh_OqeA'] },
          { id: 'forms', name: 'Forms', description: 'Handling forms', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['Z1RJmh_OqeA'] },
        ],
      },
    ],
  },
  spring: {
    id: 'spring',
    name: 'Spring Framework',
    icon: '🍃',
    color: 'neon-green',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Spring Basics',
        description: 'Fundamentals of Spring',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Spring', description: 'What is Spring?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['s1pL1p1hI9M'] },
          { id: 'ioc', name: 'IoC Container', description: 'Inversion of Control', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['s1pL1p1hI9M'] },
          { id: 'di', name: 'Dependency Injection', description: 'DI pattern', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['s1pL1p1hI9M'] },
          { id: 'beans', name: 'Spring Beans', description: 'Bean management', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['s1pL1p1hI9M'] },
        ],
      },
    ],
  },
  nestjs: {
    id: 'nestjs',
    name: 'NestJS',
    icon: '🪺',
    color: 'neon-red',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'NestJS Basics',
        description: 'Fundamentals of NestJS',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to NestJS', description: 'What is NestJS?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['0M8AYU_hPas'] },
          { id: 'modules', name: 'Modules', description: 'Module system', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['0M8AYU_hPas'] },
          { id: 'controllers', name: 'Controllers', description: 'Route handlers', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['0M8AYU_hPas'] },
          { id: 'providers', name: 'Providers', description: 'Services and DI', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['0M8AYU_hPas'] },
        ],
      },
    ],
  },
  mongodb: {
    id: 'mongodb',
    name: 'MongoDB',
    icon: '🍃',
    color: 'neon-green',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'MongoDB Basics',
        description: 'Fundamentals of MongoDB',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to MongoDB', description: 'What is MongoDB?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['-56x5UHH9FQ'] },
          { id: 'collections', name: 'Collections & Documents', description: 'Data structure', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['-56x5UHH9FQ'] },
          { id: 'queries', name: 'Queries', description: 'Finding documents', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['-56x5UHH9FQ'] },
          { id: 'indexes', name: 'Indexes', description: 'Performance optimization', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['-56x5UHH9FQ'] },
        ],
      },
    ],
  },
  postgresql: {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: '🐘',
    color: 'neon-blue',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'PostgreSQL Basics',
        description: 'Fundamentals of PostgreSQL',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to PostgreSQL', description: 'What is PostgreSQL?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['qw--VYLpxG4'] },
          { id: 'tables', name: 'Tables & Schemas', description: 'Database structure', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['qw--VYLpxG4'] },
          { id: 'queries', name: 'SQL Queries', description: 'SELECT, INSERT, UPDATE', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['qw--VYLpxG4'] },
          { id: 'joins', name: 'JOINs', description: 'Combining tables', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['qw--VYLpxG4'] },
        ],
      },
    ],
  },
  redis: {
    id: 'redis',
    name: 'Redis',
    icon: '🔴',
    color: 'neon-red',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Redis Basics',
        description: 'Fundamentals of Redis',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Redis', description: 'What is Redis?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['G1rOthIU-uo'] },
          { id: 'data-types', name: 'Data Types', description: 'Strings, hashes, lists', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['G1rOthIU-uo'] },
          { id: 'commands', name: 'Redis Commands', description: 'Basic commands', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['G1rOthIU-uo'] },
          { id: 'pub-sub', name: 'Pub/Sub', description: 'Publish-subscribe', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['G1rOthIU-uo'] },
        ],
      },
    ],
  },
  docker: {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    color: 'neon-blue',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Docker Basics',
        description: 'Fundamentals of Docker',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Docker', description: 'What is Docker?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['fqMOX6JJhGo'] },
          { id: 'containers', name: 'Containers', description: 'Container basics', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['fqMOX6JJhGo'] },
          { id: 'images', name: 'Docker Images', description: 'Image management', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['fqMOX6JJhGo'] },
          { id: 'dockerfile', name: 'Dockerfile', description: 'Building images', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['fqMOX6JJhGo'] },
        ],
      },
    ],
  },
  kubernetes: {
    id: 'kubernetes',
    name: 'Kubernetes',
    icon: '☸️',
    color: 'neon-blue',
    domain: 'backend',
    units: [
      {
        id: 'basics',
        name: 'Kubernetes Basics',
        description: 'Fundamentals of Kubernetes',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Kubernetes', description: 'What is Kubernetes?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['PH-2NfSrDoo'] },
          { id: 'pods', name: 'Pods', description: 'Pod basics', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['PH-2NfSrDoo'] },
          { id: 'services', name: 'Services', description: 'Service types', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['PH-2NfSrDoo'] },
          { id: 'deployments', name: 'Deployments', description: 'Deployment management', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['PH-2NfSrDoo'] },
        ],
      },
    ],
  },
  
  // ============ AIML DOMAIN ============
  'ml-basics': {
    id: 'ml-basics',
    name: 'Machine Learning Basics',
    icon: '🧠',
    color: 'neon-purple',
    domain: 'aiml',
    units: [
      {
        id: 'introduction',
        name: 'ML Introduction',
        description: 'Basics of machine learning',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'what-is-ml', name: 'What is Machine Learning?', description: 'ML basics', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'types', name: 'Types of ML', description: 'Supervised, unsupervised, reinforcement', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'applications', name: 'ML Applications', description: 'Real-world uses', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'workflow', name: 'ML Workflow', description: 'Data to deployment', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
      {
        id: 'supervised',
        name: 'Supervised Learning',
        description: 'Learning with labels',
        locked: true,
        completed: false,
        xpReward: 200,
        subtopics: [
          { id: 'regression', name: 'Regression', description: 'Linear, polynomial regression', locked: true, completed: false, xpReward: 50, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'classification', name: 'Classification', description: 'Logistic regression, SVM', locked: true, completed: false, xpReward: 50, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'decision-trees', name: 'Decision Trees', description: 'Tree-based models', locked: true, completed: false, xpReward: 50, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'evaluation', name: 'Model Evaluation', description: 'Metrics and validation', locked: true, completed: false, xpReward: 50, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
    ],
  },
  'deep-learning': {
    id: 'deep-learning',
    name: 'Deep Learning',
    icon: '🔬',
    color: 'neon-cyan',
    domain: 'aiml',
    units: [
      {
        id: 'introduction',
        name: 'Deep Learning Introduction',
        description: 'Basics of deep learning',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'what-is-dl', name: 'What is Deep Learning?', description: 'DL basics', locked: false, completed: false, xpReward: 25, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'neural-networks', name: 'Neural Networks', description: 'NN fundamentals', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'backpropagation', name: 'Backpropagation', description: 'Training neural networks', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'activation', name: 'Activation Functions', description: 'ReLU, sigmoid, tanh', locked: false, completed: false, xpReward: 25, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
    ],
  },
  'neural-networks': {
    id: 'neural-networks',
    name: 'Neural Networks',
    icon: '🧬',
    color: 'neon-pink',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'NN Basics',
        description: 'Fundamentals of neural networks',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to NNs', description: 'What are neural networks?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'perceptron', name: 'Perceptron', description: 'Single neuron', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'mlp', name: 'Multi-Layer Perceptron', description: 'Deep networks', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'training', name: 'Training NNs', description: 'Gradient descent', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
    ],
  },
  nlp: {
    id: 'nlp',
    name: 'Natural Language Processing',
    icon: '💬',
    color: 'neon-blue',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'NLP Basics',
        description: 'Fundamentals of NLP',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to NLP', description: 'What is NLP?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'tokenization', name: 'Tokenization', description: 'Text preprocessing', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'embeddings', name: 'Word Embeddings', description: 'Word2Vec, GloVe', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'transformers', name: 'Transformers', description: 'BERT, GPT', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
    ],
  },
  'computer-vision': {
    id: 'computer-vision',
    name: 'Computer Vision',
    icon: '👁️',
    color: 'neon-green',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'CV Basics',
        description: 'Fundamentals of computer vision',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to CV', description: 'What is computer vision?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['aircAruvnKk'] },
          { id: 'image-processing', name: 'Image Processing', description: 'Image manipulation', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['aircAruvnKk'] },
          { id: 'cnn', name: 'Convolutional Neural Networks', description: 'CNNs for images', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['aircAruvnKk'] },
          { id: 'object-detection', name: 'Object Detection', description: 'YOLO, R-CNN', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['aircAruvnKk'] },
        ],
      },
    ],
  },
  tensorflow: {
    id: 'tensorflow',
    name: 'TensorFlow',
    icon: '🔥',
    color: 'neon-orange',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'TensorFlow Basics',
        description: 'Fundamentals of TensorFlow',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to TensorFlow', description: 'What is TensorFlow?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['tPYj3fFJGjk'] },
          { id: 'tensors', name: 'Tensors', description: 'Tensor basics', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['tPYj3fFJGjk'] },
          { id: 'models', name: 'Building Models', description: 'Creating models', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['tPYj3fFJGjk'] },
          { id: 'training', name: 'Training Models', description: 'Model training', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['tPYj3fFJGjk'] },
        ],
      },
    ],
  },
  pytorch: {
    id: 'pytorch',
    name: 'PyTorch',
    icon: '🔥',
    color: 'neon-red',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'PyTorch Basics',
        description: 'Fundamentals of PyTorch',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to PyTorch', description: 'What is PyTorch?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['V_xro1bcAuA'] },
          { id: 'tensors', name: 'Tensors', description: 'PyTorch tensors', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['V_xro1bcAuA'] },
          { id: 'autograd', name: 'Autograd', description: 'Automatic differentiation', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['V_xro1bcAuA'] },
          { id: 'nn-module', name: 'nn.Module', description: 'Building neural networks', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['V_xro1bcAuA'] },
        ],
      },
    ],
  },
  'data-science': {
    id: 'data-science',
    name: 'Data Science',
    icon: '📊',
    color: 'neon-yellow',
    domain: 'aiml',
    units: [
      {
        id: 'basics',
        name: 'Data Science Basics',
        description: 'Fundamentals of data science',
        locked: false,
        completed: false,
        xpReward: 100,
        subtopics: [
          { id: 'intro', name: 'Introduction to Data Science', description: 'What is data science?', locked: false, completed: false, xpReward: 20, order: 1, youtubeVideos: ['ua-CiDNNJ30'] },
          { id: 'pandas', name: 'Pandas', description: 'Data manipulation', locked: false, completed: false, xpReward: 25, order: 2, youtubeVideos: ['ua-CiDNNJ30'] },
          { id: 'numpy', name: 'NumPy', description: 'Numerical computing', locked: false, completed: false, xpReward: 25, order: 3, youtubeVideos: ['ua-CiDNNJ30'] },
          { id: 'visualization', name: 'Data Visualization', description: 'Matplotlib, Seaborn', locked: false, completed: false, xpReward: 30, order: 4, youtubeVideos: ['ua-CiDNNJ30'] },
        ],
      },
    ],
  },
}
